name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.4'
      - name: Install dependencies
        run: |
          pip install sphinx==7.2.6 pydata-sphinx-theme==0.15.2 numpy==1.25.2 scipy==1.10.0 numpydoc==1.6.0
      - name: Sphinx build
        run: |
          rm -rf docs/source/generated
          sphinx-apidoc -o docs/source/generated simplepyml -t docs/source/_templates -d -1 -eMT
          sphinx-build docs/source _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true